Repository react-native-community/releases, pull requests merged in 2020-03, with the labels that each got.

#165 Document current release process
  README.md
  docs/branch-strategy.monopic
  docs/generate-changelog.md
  docs/publish-release.md
  docs/release-process.md
  docs/upgrade-helper.md
  package.json
Labels: release status

#171 [docs] Incorporate more feedback
  README.md
  docs/generate-changelog.md
  docs/publish-release.md
  docs/release-process.md
Labels: enhancement

#172 [docs] Add generate-changelog doc
  docs/generate-changelog.md
  package.json
  scripts/changelog-generator.ts
Labels: enhancement

#173 Add failed section
  scripts/changelog-generator.ts
Labels: enhancement

#174 changelog: move around some misplaced commits
  CHANGELOG.md
Labels: enhancement

#175 Address unknown changelog entries
  CHANGELOG.md
Labels: changelog entry, enhancement

#177 changelog: removed duplicates and fixed inconsistent formatting
  CHANGELOG.md
Labels: enhancement

#166 New 0.62.0 changelog
  .markdownlint.json
  CHANGELOG.md
Labels: changelog entry
